Repository puppetlabs/puppetlabs-puppet_conf, pull requests merged in 2019-12, with the labels that each got.

#86 pdksync - FM-8499 remove ubuntu 14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#87 pdksync - "MODULES-10242 Add ubuntu14 support back to the modules"
  metadata.json
  provision.yaml
Labels: feature

#88 pdksync - "MODULES-10236 disable deploy_to_forge for the module"
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#89 Merge back for release version v0.5.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#90 (maint) - v0.6.0 Relese Mergeback
  CHANGELOG.md
  metadata.json
Labels: maintenance

#94 Run pdk update to obtain .travis.yml template update
  .travis.yml
  metadata.json
Labels: maintenance

#93 pdksync - FM-8834 - Add GitHub action workflow
  .github/workflows/release.yml
Labels: maintenance
